global:
  scrape_interval:     15s # How frequently to scrape targets from this job.
  evaluation_interval: 15s # How frequently to evaluate rules.

  external_labels:
    monitor: 'monitor'

rule_files:
  - 'prometheus.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'prometheus-alertmanager-container:9093'

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['prometheus-container:9090', 'python-prometheus-client-container:8000']
